# Site settings
title: MrMahesh.com
email: your-email@example.com
description: "A professional showcase of IT Homelab projects and technical documentation."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mrmahesh.com" # the base hostname & protocol for your site

# Add this to the top-level of your _config.yml
plugins:
  - jekyll-paginate-v2

# Build settings
markdown: kramdown
theme: minima # You can remove this if you aren't using the default theme

# Define your Custom Content Types (Collections)
collections:
  # The 'projects' collection will contain your homelab reports.
  projects:
    output: true
    permalink: /projects/:path/
  # The 'posts' collection is Jekyll's default for your blog/updates
  posts:
    output: true
    permalink: /updates/:year/:month/:day/:title/
  cms:
    output: true
    permalink: /cms/:path/

# --- Pagination Settings ---
# You can edit these settings, especially 'per_page'.
pagination:
  enabled: true
  per_page: 3 # Number of posts to show per page
  permalink: '/projects/page/:num/' # The URL structure for paginated pages
  collection: 'projects' # The collection to paginate
  sort_field: 'date'
  sort_reverse: true

# Files to include in the build process
include:
  - admin

# Files excluded from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

kramdown:
  hard_wrap: true